version: '3.5'
# FershoUno
services:
    db:
      image: mariadb:latest
      container_name: wordpress_db
      volumes:
        - data:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=c486f6ccdb74478956d3b23752b9dc2b
        - MYSQL_DATABASE=wordpress
        - MYSQL_USER=administrador
        - MYSQL_PASSWORD=c486f6ccdb74478956d3b23752b9dc2b
      networks:
          services:
            ipv4_address: 10.0.3.10
    web:
      image: wordpress:latest
      container_name: wordpress_web
      depends_on:
        - db
      volumes:
        - ./target:/var/www/html
      environment:
        - WORDPRESS_DB_USER=administrador
        - WORDPRESS_DB_PASSWORD=c486f6ccdb74478956d3b23752b9dc2b
        - WORDPRESS_DB_HOST=db
      ports:
        - 8080:80
      networks:
        services:
          ipv4_address: 10.0.3.11

volumes:
    data:
networks:
  services:
    name: wordpress_net
    ipam:
      config:
        - subnet: 10.0.3.0/24
