version: '3'
# FershoUno
services:
    db:
        image: mariadb:latest
        volumes:
            - data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=c486f6ccdb74478956d3b23752b9dc2b
            - MYSQL_DATABASE=wordpress
            - MYSQL_USER=administrador
            - MYSQL_PASSWORD=c486f6ccdb74478956d3b23752b9dc2b
    web:
        image: wordpress:latest
        depends_on:
            - db
        volumes:
            - ./target:/var/www/html
        environment:
            - WORDPRESS_DB_USER=administrador
            - WORDPRESS_DB_PASSWORD=c486f6ccdb74478956d3b23752b9dc2b
            - WORDPRESS_DB_HOST=db
        ports:
            - 8080:80

volumes:
    data:
