version: '3.5'
# FershoUno
services:

  db:
    image: mariadb:latest
    container_name: nextcloud_db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW 
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=e57fdd90fc06a8e9ff198e3654fae712
      - MYSQL_PASSWORD=e57fdd90fc06a8e9ff198e3654fae712
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      services:
        ipv4_address: 10.0.2.10

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud_web
    restart: always
    ports:
      - "8000:80"
    links:
      - db
    volumes:
      - ./nextcloud/config:/var/www/html/config
      - ./nextcloud/data:/var/www/html/data 
      - ./nextcloud/custom_apps:/var/www/html/custom_apps
      - ./nextcloud/themes:/var/www/html/themes
    environment:
      - MYSQL_PASSWORD=e57fdd90fc06a8e9ff198e3654fae712
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    networks:
      services:
        ipv4_address: 10.0.2.11

volumes:
  nextcloud:
  db:      
networks:
  services:
    name: nextcloud_net
    ipam:
      config:
        - subnet: 10.0.2.0/24
