version: '3.5'
# FershoUno
services:
  dokuwiki:
    container_name: dokuwiki_web
    image: docker.io/bitnami/dokuwiki:latest
    ports:
      - '9000:8080'
    volumes:
      - 'dokuwiki_data:/bitnami/dokuwiki'
    environment:
      - DOKUWIKI_USERNAME=administrador
      - DOKUWIKI_FULL_NAME=Administrador Dokuwiki
      - DOKUWIKI_PASSWORD=b29fe4587166a22e36be619aad4ceb75
      - DOKUWIKI_EMAIL=administrador@example.com
      - DOKUWIKI_WIKI_NAME=Personal Dokuwiki
    networks:
      services:
        ipv4_address: 10.0.1.10
     
volumes:
  dokuwiki_data:
    driver: local
networks:
  services:
    name: dokuwiki_net
    ipam:
      config:
        - subnet: 10.0.1.0/24
  
